# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import coord_service_pb2 as coord__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coord_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PathServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartEnv = channel.unary_unary(
                '/getpathservice.PathService/StartEnv',
                request_serializer=coord__service__pb2.Empty.SerializeToString,
                response_deserializer=coord__service__pb2.StartMessage.FromString,
                _registered_method=True)
        self.EndEnv = channel.unary_unary(
                '/getpathservice.PathService/EndEnv',
                request_serializer=coord__service__pb2.Empty.SerializeToString,
                response_deserializer=coord__service__pb2.EndMessage.FromString,
                _registered_method=True)
        self.GetPathToTarget = channel.unary_unary(
                '/getpathservice.PathService/GetPathToTarget',
                request_serializer=coord__service__pb2.InitialData.SerializeToString,
                response_deserializer=coord__service__pb2.PathResponse.FromString,
                _registered_method=True)


class PathServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartEnv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndEnv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPathToTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PathServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartEnv': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEnv,
                    request_deserializer=coord__service__pb2.Empty.FromString,
                    response_serializer=coord__service__pb2.StartMessage.SerializeToString,
            ),
            'EndEnv': grpc.unary_unary_rpc_method_handler(
                    servicer.EndEnv,
                    request_deserializer=coord__service__pb2.Empty.FromString,
                    response_serializer=coord__service__pb2.EndMessage.SerializeToString,
            ),
            'GetPathToTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPathToTarget,
                    request_deserializer=coord__service__pb2.InitialData.FromString,
                    response_serializer=coord__service__pb2.PathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'getpathservice.PathService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('getpathservice.PathService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PathService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartEnv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/getpathservice.PathService/StartEnv',
            coord__service__pb2.Empty.SerializeToString,
            coord__service__pb2.StartMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndEnv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/getpathservice.PathService/EndEnv',
            coord__service__pb2.Empty.SerializeToString,
            coord__service__pb2.EndMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPathToTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/getpathservice.PathService/GetPathToTarget',
            coord__service__pb2.InitialData.SerializeToString,
            coord__service__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
