# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coord_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'coord_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63oord_service.proto\x12\x0egetpathservice\"\x07\n\x05\x45mpty\"2\n\x0cStartMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tmax_coord\x18\x02 \x03(\x02\"\x1d\n\nEndMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"J\n\x0bInitialData\x12\x13\n\x0bstart_coord\x18\x01 \x03(\x02\x12\x14\n\x0ctarget_coord\x18\x02 \x03(\x02\x12\x10\n\x08timestep\x18\x03 \x01(\x05\"\x82\x01\n\x0cPathResponse\x12\r\n\x05\x65\x64ges\x18\x01 \x03(\x05\x12\x12\n\nstart_type\x18\x02 \x01(\t\x12\x13\n\x0bstart_index\x18\x03 \x01(\x05\x12\x13\n\x0btarget_type\x18\x04 \x01(\t\x12\x14\n\x0ctarget_index\x18\x05 \x01(\x05\x12\x0f\n\x07message\x18\x06 \x01(\t2\xdf\x01\n\x0bPathService\x12\x41\n\x08StartEnv\x12\x15.getpathservice.Empty\x1a\x1c.getpathservice.StartMessage\"\x00\x12=\n\x06\x45ndEnv\x12\x15.getpathservice.Empty\x1a\x1a.getpathservice.EndMessage\"\x00\x12N\n\x0fGetPathToTarget\x12\x1b.getpathservice.InitialData\x1a\x1c.getpathservice.PathResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coord_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=39
  _globals['_EMPTY']._serialized_end=46
  _globals['_STARTMESSAGE']._serialized_start=48
  _globals['_STARTMESSAGE']._serialized_end=98
  _globals['_ENDMESSAGE']._serialized_start=100
  _globals['_ENDMESSAGE']._serialized_end=129
  _globals['_INITIALDATA']._serialized_start=131
  _globals['_INITIALDATA']._serialized_end=205
  _globals['_PATHRESPONSE']._serialized_start=208
  _globals['_PATHRESPONSE']._serialized_end=338
  _globals['_PATHSERVICE']._serialized_start=341
  _globals['_PATHSERVICE']._serialized_end=564
# @@protoc_insertion_point(module_scope)
