# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: getPath_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'getPath_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15getPath_service.proto\x12\x0egetpathservice\"\x07\n\x05\x45mpty\"3\n\x0cStartMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nnumOfEdges\x18\x02 \x01(\x05\"\x1d\n\nEndMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"H\n\x0bInitialData\x12\x12\n\nstart_edge\x18\x01 \x01(\x05\x12\x13\n\x0btarget_edge\x18\x02 \x01(\x05\x12\x10\n\x08timestep\x18\x03 \x01(\x05\"\x1d\n\x0cPathToTarget\x12\r\n\x05\x65\x64ges\x18\x01 \x03(\x05\x32\xdf\x01\n\x0bPathService\x12\x41\n\x08StartEnv\x12\x15.getpathservice.Empty\x1a\x1c.getpathservice.StartMessage\"\x00\x12=\n\x06\x45ndEnv\x12\x15.getpathservice.Empty\x1a\x1a.getpathservice.EndMessage\"\x00\x12N\n\x0fGetPathToTarget\x12\x1b.getpathservice.InitialData\x1a\x1c.getpathservice.PathToTarget\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'getPath_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=41
  _globals['_EMPTY']._serialized_end=48
  _globals['_STARTMESSAGE']._serialized_start=50
  _globals['_STARTMESSAGE']._serialized_end=101
  _globals['_ENDMESSAGE']._serialized_start=103
  _globals['_ENDMESSAGE']._serialized_end=132
  _globals['_INITIALDATA']._serialized_start=134
  _globals['_INITIALDATA']._serialized_end=206
  _globals['_PATHTOTARGET']._serialized_start=208
  _globals['_PATHTOTARGET']._serialized_end=237
  _globals['_PATHSERVICE']._serialized_start=240
  _globals['_PATHSERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
